
--create database djecjaigraonica;
--use djecjaigraonica;

--CREATE TABLE Dijete (
--    dijete_id INT PRIMARY KEY,
--    ime VARCHAR(50),
--    prezime VARCHAR(50)
--);
--CREATE TABLE Teta (
--    teta_id INT PRIMARY KEY,
--    ime VARCHAR(50),
--    prezime VARCHAR(50)
--);
--CREATE TABLE Skupina (
--    skupina_id INT PRIMARY KEY,
--    naziv VARCHAR(50),
--    teta_id INT,
--    FOREIGN KEY (teta_id) REFERENCES Teta(teta_id)
--);
--CREATE TABLE Sudjelovanje (
--    dijete_id INT,
--    skupina_id INT,
--    PRIMARY KEY (dijete_id, skupina_id),
--    FOREIGN KEY (dijete_id) REFERENCES Dijete(dijete_id),
--    FOREIGN KEY (skupina_id) REFERENCES Skupina(skupina_id)
--);
