----------create database doktorskaordinacija;
--------use doktorskaordinacija;

--------CREATE TABLE Doktor (
--------    id INT PRIMARY KEY,
--------    ime VARCHAR(50),
--------    prezime VARCHAR(50),
--------    specijalizacija VARCHAR(100)
--------);
------CREATE TABLE Pacijent (
------    id INT PRIMARY KEY,
------    ime VARCHAR(50),
------    prezime VARCHAR(50),
------    datum_rodenja DATE
------);

------CREATE TABLE Lijecenje (
------    id INT PRIMARY KEY,
------    doktor_id INT,
------    pacijent_id INT,
------    datum DATE,
------    dijagnoza TEXT,
------    terapija TEXT,
------    FOREIGN KEY (doktor_id) REFERENCES Doktor(id),
------    FOREIGN KEY (pacijent_id) REFERENCES Pacijent(id)
------);
----CREATE TABLE MedicinskaSestra (
----    id INT PRIMARY KEY,
----    ime VARCHAR(50),
----    prezime VARCHAR(50),
----    odjel VARCHAR(50)
----);

--CREATE TABLE SestraLijecenje (
--    sestra_id INT,
--    lijecenje_id INT,
--    PRIMARY KEY (sestra_id, lijecenje_id),
--    FOREIGN KEY (sestra_id) REFERENCES MedicinskaSestra(id),
--    FOREIGN KEY (lijecenje_id) REFERENCES Lijecenje(id)
--);
