--------create database trgovackicentar;
--------use trgovackicentar;a

------CREATE TABLE Trgovina (
------    id INT PRIMARY KEY,
------    naziv VARCHAR(100),
------    kat INT,
------    sef_id INT
------);
----CREATE TABLE Osoba (
----    id INT PRIMARY KEY,
----    ime VARCHAR(50),
----    prezime VARCHAR(50),
----    pozicija VARCHAR(50)  -- npr. prodavač, voditelj, šef itd.
----);
--CREATE TABLE Zaposlenje (
--    trgovina_id INT,
--    osoba_id INT,
--    PRIMARY KEY (trgovina_id, osoba_id),
--    FOREIGN KEY (trgovina_id) REFERENCES Trgovina(id),
--    FOREIGN KEY (osoba_id) REFERENCES Osoba(id)
--);
