------------------create database urarsilvija;
----------------use urarsilvija;

--------------CREATE TABLE Korisnik (
--------------    sifra INT PRIMARY KEY,
--------------    ime VARCHAR(50),
--------------    prezime VARCHAR(50),
--------------    kontakt VARCHAR(100)
--------------);
------------CREATE TABLE Sat (
------------    sifra INT PRIMARY KEY,
------------    korisnik_id INT,
------------    marka VARCHAR(50),
------------    opis VARCHAR(100)
------------);
----------CREATE TABLE Popravak (
----------    sifra INT PRIMARY KEY,
----------    sat_id INT,
----------    datum_pocetka DATE,
----------    datum_zavrsetka DATE,
----------    opis VARCHAR(255)
----------);
--------CREATE TABLE Urar (
--------    id INT PRIMARY KEY,
--------    ime VARCHAR(50),
--------    prezime VARCHAR(50)
--------);
------CREATE TABLE Segrt (
------    id INT PRIMARY KEY,
------    ime VARCHAR(50),
------    prezime VARCHAR(50),
------    urar_id INT,
------    FOREIGN KEY (urar_id) REFERENCES Urar(id)
------);
----CREATE TABLE Segrt (
----    id INT PRIMARY KEY,
----    ime VARCHAR(50),
----    prezime VARCHAR(50),
----    urar_id INT,
----    FOREIGN KEY (urar_id) REFERENCES Urar(id)
----);
--CREATE TABLE SegrtPopravak (
--    segrt_id INT,
--    popravak_id INT
--);
